#!/bin/bash
#

set -e

PREFIX=$(dirname ${0})
ACTION="install"

dpkg --clear-avail

if [ -f $PREFIX/conf/action ] ; then
  ACTION=$(< ${PREFIX}/conf/action)
fi

# echo "Acquire::http::Proxy::maker.sh.bytemark.co.uk DIRECT;" > /etc/apt/apt.conf.d/95proxy
# echo "Acquire::http::Proxy \"http://maker.sh.bytemark.co.uk:3142\";" >> /etc/apt/apt.conf.d/95proxy

if [ "upgrade" = "$ACTION" ] ; then
  #
  # Wheezy rc1 doesn't have symbiosis-xmpp
  #
  sed -i -e '/symbiosis-xmpp/d' $PREFIX/conf/wheezy-packages

  echo "I: Installing current version of Symbiosis from repo.bytemark.co.uk"
  $PREFIX/bin/apt-get-install $PREFIX/conf/current-wheezy-sources.list $PREFIX/conf/wheezy-packages

  echo "I: Performing dist-upgrade"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list

elif [ "dist-upgrade" = "$ACTION" ] ; then
  #
  # If we're upgrading from squeeze:
  #
  if [ grep -q squeeze /etc/apt/sources.list ] ; then
    echo "I: Installing squeeze version of Symbiosis from repo.bytemark.co.uk"
    $PREFIX/bin/apt-get-install $PREFIX/conf/current-squeeze-sources.list $PREFIX/conf/squeeze-packages || true

    apt-get install -f

    echo "I: Replacing squeeze sources with wheezy"
    cp $PREFIX/conf/debian-wheezy-sources.list /etc/apt/sources.list

    echo "I: clamav with squeeze is a bit ropey, so I'll clear out the freshclam stuff"
    invoke-rc.d clamav-daemon stop
    invoke-rc.d clamav-freshclam stop
    rm $VERBOSE -f /var/lib/clamav/*.cv?
  fi

  #
  # Now upgrade to wheezy.
  #
  echo "I: performing dist-upgrade"
  $PREFIX/bin/apt-get-install

  echo "I: ensuring Symbiosis packages are installed"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list $PREFIX/conf/wheezy-packages
else 



  echo "I: Installing latest version of Symbiosis from maker.sh.bytemark.co.uk"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list $PREFIX/conf/wheezy-packages
fi

