#!/bin/bash
#
#  Update the local system with apt-get so that all pending
# package update are completed.
#
#  This uses a special sources.list file to ensure that we only
# update packages that we expect to update.
#
#  See full manpage at the foot of this script.
#
# Steve
# --

set -e

#
#  PATH updating
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

#
#  The sources list we update from.
#
SOURCES="/etc/apt/sources.list.d/test-sources.list"


#
#  The email address to notify, if any.
#
EMAIL=root@`hostname`

cat > $SOURCES <<EOF
deb http://maker.sh.bytemark.co.uk/archives/symbiosis-squeeze/latest/ ./
deb http://maker.sh.bytemark.co.uk/archives/ruby-cracklib/squeeze/latest/ ./
deb http://maker.sh.bytemark.co.uk/archives/netlinkrb/squeeze/latest/ ./

EOF

#
#  Minimise debconf front-end
#
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND

#
#  The options to use by default.
#
OPTIONS="-o \"APT::Get::AllowUnauthenticated=true\" -o \"DPkg::Options::=--force-confold\""

#
#  Sanity check that we're on a Debian/Ubuntu host.
#
if [ ! -x /usr/bin/apt-get ] ; then
    echo "/usr/bin/apt-get missing or non-executable."
    exit 1
fi

#
#  Make sure we have our sources.list present.
#
if [ ! -e "$SOURCES" ] ; then
    echo "$SOURCES missing"
    exit 1
fi

#
#  Make sure we're root
#
if [ "$UID" -ne "0" ] ; then
    echo "You're not root."
    exit 1
fi

#
#  Update our sources list and upgrade first.
#
apt-get $OPTIONS update 
apt-get $OPTIONS dist-upgrade

#
#  Now simulate a dist-upgrade so that we can see if we need to do anything
#
/usr/bin/apt-get $OPTIONS install --yes --force-yes \
  lsb-base \
  lsb-release \
  bytemark-symbiosis \
  symbiosis-backup \
  symbiosis-common \
  symbiosis-cron \
  symbiosis-email \
  symbiosis-firewall \
  symbiosis-ftpd \
  symbiosis-httpd \
  symbiosis-key \
  symbiosis-monit \
  symbiosis-mysql \
  symbiosis-pam \
  symbiosis-phpmyadmin \
  symbiosis-tinydns \
  symbiosis-updater \
  symbiosis-webmail \
  symbiosis-webmail-squirrelmail \
  openssh-server \
  postgresql \
  libmysql-ruby1.8 \
  libpgsql-ruby1.8

