#!/bin/bash

rm -f /etc/cron.d/symbiosis-monit
rm -f /etc/symbiosis/monit.d/disabled

#
# FUCK OFF DOVECOT.
#
killall -9 -u dovecot

#
# Make sure clamav + spamassassin stay running
#

touch /srv/$(hostname)/config/anti{spam,virus}

export TERM=dummy
exec /usr/sbin/symbiosis-monit --verbose

