#!/bin/bash

rm -f /etc/cron.d/symbiosis-monit
rm -f /etc/symbiosis/monit.d/disabled

do_monit() {
  #
  # Make sure clamav + spamassassin stay running
  #

  touch /srv/$(hostname)/config/anti{spam,virus}

  /usr/sbin/symbiosis-monit 
}

#
# Have a couple of goes running monit 
#
trap do_monit ERR

do_monit
