#!/bin/bash

set -e

export LC_ALL="en_GB.UTF-8"

#
# Timeout commands after 15 minutes .. kill after 20 if the TERM isn't
# respected.
#
update-alternatives --set ruby /usr/bin/ruby1.9.1
/usr/bin/timeout -k 20m 15m /usr/bin/symbiosis-test
