#!/bin/bash
# 
#

#
# This script runs through and executes each program to test its basic functionality.
#
set -exv

#
# We expect this will exit 1 when running on a non-Bytemark IP.  So lets check
# the output.
#
ans=$(is-bytemark-ip || true)
[ "$ans" = "0" -o "$ans" = "1" ]

#
# Check backup space finding.
#
ans=$(which-backup-space 89.16.174.65)
[ "$ans" = "example.backup.bytemark.co.uk" ]

#
# Check password encryption
#
pw="correct horse battery staple"
ans=$(symbiosis-encrypt-password "$pw")
ruby -e "ans='$ans'.sub(/^\{CRYPT\}/,'') ; exit '$pw'.crypt(ans) == ans"

#
# This just returns the IP address
#
symbiosis-ip --verbose

#
# Run all crontabs
#
symbiosis-all-crontabs --verbose


#
# Test our crontab runner
#
echo "@daily echo foo" > /tmp/crontab
symbiosis-crontab --test /tmp/crontab


symbiosis-ip --verbose
symbiosis-crontab --verbose 
# symbiosis-apache-logger
symbiosis-create-mass-hosting-sites --verbose
symbiosis-create-sites --verbose 
symbiosis-generate-stats --verbose 
symbiosis-rotate-logs --verbose 
symbiosis-configure-ips --verbose

#
# Set the mailbox password
#
echo "$ans" > /srv/$(hostname)/mailboxes/root/password
chown admin.admin /srv/$(hostname)/mailboxes/root/password

#
# Password weakness tester
#
symbiosis-password-test --verbose

#
# Test the mailbox password (set above)
#
echo -e -n "root@$(hostname)\0$pw\0" | symbiosis-check-mailbox-password 3<&0

#
# Disable the DNS uploader.
#
rm -rf /root/BytemarkDNS/update
echo "exit 0" > /root/BytemarkDNS/update
symbiosis-dns-generate --verbose

#
# Check the FTP password
#
echo "$ans" > /srv/$(hostname)/config/ftp-password
chown admin.admin /srv/$(hostname)/config/ftp-password
AUTHD_ACCOUNT="$(hostname)" AUTHD_PASSWORD="$pw" AUTHD_REMOTE_IP="1.2.3.4" symbiosis-check-ftp-password

#
# Now check the firewall scripts
#
symbiosis-firewall --verbose
symbiosis-firewall-blacklist --verbose
symbiosis-firewall-whitelist --verbose 


#
# And finally our updater.
#
echo QUIET="" > /etc/symbiosis/updater
echo SSH_TTY="foo" > /etc/symbiosis/updater
symbiosis-updater
