#!/bin/bash
# 
#

#
# This script runs through and executes each program to test its basic functionality.
#
set -ex

#
# We expect this will exit 1 when running on a non-Bytemark IP.  So lets check the output.
#
ans=$(is-bytemark-ip)
[ "$ans" = "0" -o "$ans" = "1" ]

#
# Check backup space finding.
#
ans=$(which-backup-space 89.16.174.65)
[ "$ans" = "example.backup.bytemark.co.uk" ]

#
# Check password encryption
#
pw="correct horse battery staple"
ans=$(symbiosis-encrypt-password "$pw")
ruby -e "ans='$ans'.sub(/^\{CRYPT\}/,'') ; exit '$pw'.crypt(ans) == ans"

symbiosis-ip -v
symbiosis-crontab -v 
# symbiosis-apache-logger
symbiosis-create-mass-hosting-sites -v
symbiosis-create-sites -v 
symbiosis-generate-stats -v 
symbiosis-rotate-logs -v 
symbiosis-configure-ips -v
symbiosis-password-test -v
symbiosis-dns-generate -v
# symbiosis-check-mailbox-password -v
symbiosis-firewall -v
symbiosis-firewall-blacklist -v
symbiosis-firewall-whitelist -v 
# symbiosis-check-ftp-password -v
symbiosis-updater -v
