#!/bin/sh

. $(dirname $0)/common

echo -e "\nEHLO $(hostname)\nQUIT" | socat EXEC:"socat-scripter",fdin=3,fdout=4 TCP:$IP:25 

echo -e "\nEHLO $(hostname)\nQUIT" | socat EXEC:"socat-scripter",fdin=3,fdout=4 OPENSSL:$IP:465,verify=0 

